export const defaultValues = {
  challanNo: `DC-${new Date().getFullYear()}-${String(Math.floor(Math.random() * 1000)).padStart(3, '0')}`,
  date: new Date().toISOString().split('T')[0],
  psdOrderNumber: '',
  workOrderNumber: '',
  workOrderDate: '',
  code: '',
  from: {
    name: '',
    address: '',
    gstin: '',
    contactPerson: '',
    contactNumber: '',
    email: '',
  },
  to: {
    name: '',
    address: '',
    gstin: '',
    contactPerson: '',
    contactNumber: '',
    email: '',
  },
  items: [{
    id: crypto.randomUUID(),
    srNo: 1,
    description: '',
    quantity: 1,
    unit: 'pcs',
    remarks: '',
    hsnCode: '',
    uom: '',
    pricePerUnit: 0,
    totalPrice: 0
  }],
  transport: {
    name: '',
    gstin: '',
    vehicleType: '',
    vehicleNumber: '',
    lrNo: '',
    lrDate: '',
    eWayBillNumber: '',
  },
  deliveryTerms: '',
  transitInsurance: '',
  authorizedSignatory: '',
  totalAmount: 0
};